### ISSUE TITLE
License + README

### ISSUE THREAD

**Issue by Stebalien** [ipfs-shipyard/DAGger#1]

**Comment by momack2** [comment]
@ribasushi is this WIP, or is this repo not live yet? Was looking for the place to track work for this chunking tool so I can add a todo about creating a website like https://ipfs.github.io/public-gateway-checker/ that looks across chunking algorithms and benchmarks as the community adds more

**Comment by ribasushi** [comment]
@momack2 repo reflects wip of the code, but is not a live history. This all is to be renamed with a cleaned up history to be `ipld-dagger`. There are just a few more dependencies remaining to get this properly shipped, trying my damnested...

The best ticket to track currently is https://github.com/ipld/DAGger/issues/1

**Comment by ribasushi** [comment]
LICENSE in place, so is basic README, the remainder tracked in #5
