### ISSUE TITLE
nul is a terrible name

### ISSUE THREAD

**Issue by Artoria2e5** [ipfs-shipyard/DAGger#6]
My version of `go` (go1.14.5 darwin/amd64) is unhappy with a pathname with `nul` in it:

> package github.com/ipfs-shipyard/DAGger/internal/dagger/collector/nul: github.com/ipfs-shipyard/DAGger/internal/dagger/collector/nul: invalid import path: malformed import path "github.com/ipfs-shipyard/DAGger/internal/dagger/collector/nul": disallowed path element "nul"

**Comment by ribasushi** [comment]
Ah, indeed! I'll fix this in the upcoming overhaul.

Note that work on this repo is suspended for the next few weeks/month, but I do fully intend to get back to this project.

**Comment by ribasushi** [comment]
Addressed in a pre-alpha branch: https://github.com/ipfs/distributed-wikipedia-mirror/issues/71#issuecomment-662314032
